# Generated by Django 4.2.3 on 2023-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='код подтверждения почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='страна'),
        ),
    ]
