# Generated by Django 4.2.3 on 2023-08-12 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'категория', 'verbose_name_plural': 'категория'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default=datetime.datetime(2023, 8, 12, 21, 1, 19, 496302, tzinfo=datetime.timezone.utc), max_length=15000, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=datetime.datetime(2023, 8, 12, 21, 3, 54, 967457, tzinfo=datetime.timezone.utc), max_length=150, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_change',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменений'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default='', max_length=15500, verbose_name='Описание товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=3, max_length=155, verbose_name='Наименование товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
