# Generated by Django 4.2.3 on 2023-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
