# Generated by Django 4.2.3 on 2023-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
