# Generated by Django 4.2.3 on 2023-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_active_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_version',
        ),
        migrations.AddField(
            model_name='product',
            name='active_versions',
            field=models.ManyToManyField(related_name='products_with_active_version', to='catalog.version'),
        ),
    ]
